### ISSUE TITLE
urlteam_2020-12-28-03-17-02 Archive already exists!

### ISSUE THREAD

**Issue by DamianMorozov** [utkusen/urlhunter#12]
I have download this repo.
I have download xz-5.2.5-windows.zip. Install files to c:\Windows\System32.
I have goo message from: > `xz --help`
First time run was downloaded the archives to archives\urlteam_2020-12-28-03-17-02\
But then i have errors: `go run main.go -date latest -keywords keywords.txt -o out.txt`
```
Search starting for: latest
urlteam_2020-12-28-03-17-02 Archive already exists!
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.searchFile(0xc0001a5380, 0x37, 0xc0001adbc0, 0x14, 0xc000010118, 0x7)
        ../urlhunter/main.go:201 +0xc5c
main.getArchive(0xc000300000, 0x172e4, 0x1fe00, 0xc0000100a8, 0x6, 0xc0000100f0, 0xc, 0xc000010118, 0x7)
        ../urlhunter/main.go:194 +0xb2f
main.main()
        ../urlhunter/main.go:94 +0x387
exit status 2
```

**Comment by utkusen** [comment]
Could you please try to use the compiled-binary for Windows? https://github.com/utkusen/urlhunter/releases

**Comment by DamianMorozov** [comment]
Downloaded and unpack `urlhunter_0.1.1_Windows_amd64.zip`.
Copied the `archives\urlteam_2020-12-28-03-17-02\` to the new folder.
Copied the `keywords.txt.`
Run the command `urlhunter.exe -date latest -keywords keywords.txt -o out.txt`
And then i have the same error.
`Search starting for: latest
urlteam_2020-12-28-03-17-02 Archive already exists!
panic: runtime error: index out of range [1] with length 1`

**Comment by Avadanii** [comment]
Who are you?

**Comment by DamianMorozov** [comment]
Can you solve that issues?

**Comment by utkusen** [comment]
I will check it soon

**Comment by DamianMorozov** [comment]
Hello, do you have any news?

**Comment by rzhade3** [comment]
Hi @DamianMorozov! Looks like the issue is that we're splitting the filename on `/` whereas on Windows the default path separator is `\`. 

If we change the `strings.Split` on that line to a [`filepath.Split`](https://golang.org/pkg/path/filepath/#example_Split) followed by a `filepath.Join`, it should fix this bug.

**Comment by rzhade3** [comment]
@utkusen Could you please release a new version of URLHunter with the patch in #13 included?
